### ISSUE TITLE
Data contains just URLs

### ISSUE THREAD

**Issue by jarekkopec** [havanagrawal/GoodreadsScraper#17]
.JL file containst just URLs of the books, no other fields. Is it caused by some changes in Goodreads' interface?

**Comment by havanagrawal** [comment]
Hello [bekonowicz](https://github.com/bekonowicz), thanks for raising this issue! Goodreads did in fact update their website, I've updated the book scraper to correctly extract fields again.

I'll update the author scraper in the next few commits!

**Comment by havanagrawal** [comment]
Looks like author pages were not affected. I updated the fields names to be consistent. Closing this issue! Thanks again :)

**Comment by sherbert-lemon** [comment]
Hey, I'm having issues where the .jl book file seems to be sporadically displaying some results with only the URL while others are complete with all fields — authors.jl seems to be unaffected. Just a heads up!
